CREATE TABLE quotes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    quote TEXT NOT NULL, 
    vote INTEGER DEFAULT 0
);

INSERT INTO quotes (quote) VALUES
("Bitcoin is a swarm of cyber hornets serving the goddess of wisdom, feeding on the fire of truth, exponentially growing ever smarter, faster, and stronger behind a wall of encrypted energy."),
("Like Bitcoin, living things are volatile. Dead things, not so much."),
("There are decades when nothing happens, and there are weeks when Bitcoin happens."),
("All my best investments were in networks that everyone needed, no one could stop, and few understood. Bitcoin is the monetary network."),
("Imagine a world where everyone used something fair & equitable to settle their economic differences."),
("The destiny of money is to be encrypted."),
("Bitcoin is the dominant digital monetary network. The next billion members will pay trillions to join. You might want to join first."),
("A designer knows he has achieved perfection when there is nothing left to take away."),
("It doesn’t matter if it is quick if it’s the wrong answer."),
("Bitcoin is worth all the money in the world."),
("Bitcoin is an ark of encrypted energy to escape the currency flood."),
("Bitcoin is the most efficient system in the history of mankind for channeling energy through time and space."),
("The magic of Bitcoin isn’t the transfer of money to someone 10,000 miles away – it is the transfer of money to someone 10,000 days away."),
("Bitcoin is The Monetary Network. People with money will join. Then people with money will have to join."),
("Bitcoin is money. Everything else is credit."),
("Bitcoin is the solution. Everything else is noise."),
("Bitcoin is digital gold – growing harder, smarter, faster, & stronger due to the relentless progression of technology."),
("21st century investors lost trillions clinging to 20th century ideas. Gold peaked in the 19th century. Buy Bitcoin."),
("My formula for success is rise early, work late, and buy Bitcoin."),
("I’m not so naive as to think that everybody always succeeds, right? I mean, half of Shakespeare’s stories are tragedies – right?"),
("Whenever teenage girls and corporate CEOs covet the same new technology, something extraordinary is happening."),
("The only thing better than Bitcoin is more Bitcoin."),
("Bitcoin - There is No Second Best."),
("$ell the Past. ₿uy the Future."),
("Bitcoin is Better Money."),
("In time, you'll forget the price you paid but remember the Bitcoin you bought."),
("Thank You, Satoshi."),
("Pizza keeps getting cheaper on a Bitcoin Standard."),
("Nothing is more powerful than an idea whose time has come."),
("Stay Humble. Stack Sats."),
("You do not sell your Bitcoin."),
("Bitcoin is Cyber Manhattan."),
("1 BTC = 1 BTC."),
("Nothing has created more wealth in the past decade than technologies banned in China."),
("Volatility is a gift to the faithful."),
("If you are not buying bitcoin at the top, you are leaving money on the table."),
("The future of money will be determined by physics."),
("Satoshi gave us a game we can all win."),
("The money is great. The mission is even greater."),
("Bitcoin is Rules Without Rulers."),
("Bitcoin benefits from all forms of investment by all types of entities, and should welcome everyone."),
("The Bitcoin price is set by those with more money and less knowledge than you. In time, they will get the knowledge and you will get the money.");


