CREATE TABLE quotes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    quote TEXT NOT NULL, 
    vote INTEGER DEFAULT 0
);

INSERT INTO quotes (quote) VALUES
("Bitcoin is a bank in cyberspace, run by incorruptible software, offering a global, affordable, simple and secure savings account to billions of people that don’t have the option or desire to run their own hedge fund."),
("Bitcoin is a swarm of cyber hornets serving the goddess of wisdom, feeding on the fire of truth, exponentially growing ever smarter, faster, and stronger behind a wall of encrypted energy."),
("Like Bitcoin, living things are volatile. Dead things, not so much."),
("There are decades when nothing happens, and there are weeks when Bitcoin happens."),
("Google is what happens when we pool information energy on a software network. Everyone understands this. Bitcoin is what happens when we pool monetary energy on a software network. Few understand this."),
("All my best investments were in networks that everyone needed, no one could stop, and few understood. Bitcoin is the monetary network."),
("The signal is monetary expansion everywhere. The problem is people are going to lose half their wealth in a few years. The solution is Bitcoin. The rest is noise."),
("The old ways of teaching are slow and expensive. But with mobile, cost plummets, access broadens, and pedagogy rises."),
("Bitcoin is the first software network capable of storing all the monetary energy in the world with no loss of power over time and negligible transmission loss. Assuming broad adoption, that would make it the most valuable invention of the modern era. Few understand this."),
("Imagine a world where everyone used something fair & equitable to settle their economic differences."),
("The destiny of money is to be encrypted."),
("Bitcoin is the dominant digital monetary network. The next billion members will pay trillions to join. You might want to join first."),
("A designer knows he has achieved perfection when there is nothing left to take away."),
("It doesn’t matter if it is quick if it’s the wrong answer."),
("Imagine a world where everyone used something fair & equitable to settle their economic differences."),
("Bitcoin links together 8 billion people, links together a hundred million companies, it synchronizes the world across political jurisdictions, and it returns rationality to the entire financial system, and it returns freedom and property rights to the entire human race."),
("Bitcoin is an ark of encrypted energy to escape the currency flood."),
("Bitcoin is the most efficient system in the history of mankind for channeling energy through time and space."),
("The magic of Bitcoin isn’t the transfer of money to someone 10,000 miles away – it is the transfer of money to someone 10,000 days away."),
("Positive inflation drains the energy from your life. Negative interest is an attempt to stop the flow of time. Channel your energy into Bitcoin and move forward toward the future you deserve."),
("Bitcoin is The Monetary Network. People with money will join. Then people with money will have to join."),
("Bitcoin is money. Everything else is credit."),
("Bitcoin is the solution. Everything else is noise."),
("Gold miners have incentive to conceal & minimize the full extent of their reserves, increase their capacity aggressively, and mine more gold as fast as they can. They are the enemies of gold investors. It’s a hopelessly antiquated system for storing value in the 21st century."),
("Bitcoin is digital gold – growing harder, smarter, faster, & stronger due to the relentless progression of technology."),
("21st century investors lost trillions clinging to 20th century ideas. Gold peaked in the 19th century. Buy Bitcoin."),
("My formula for success is rise early, work late, and buy Bitcoin."),
("I’m not so naive as to think that everybody always succeeds, right? I mean, half of Shakespeare’s stories are tragedies – right?"),
("Whenever teenage girls and corporate CEOs covet the same new technology, something extraordinary is happening."),
("My principal professional objective is to introduce intelligence as the ubiquitous utility. I'd like to be the Thomas Edison of intelligence."),
("I have said before and I would repeat it again. If it’s not going to zero it’s going to a million."),
("A strategic digital asset policy can strengthen the US dollar, neutralize the national debt, and position America as the global leader in the 21st-century digital economy—empowering millions of businesses, driving growth, and creating trillions in value."),
("The only thing better than Bitcoin is more Bitcoin."),
("Bitcoin - There is No Second Best."),
("Bitcoin offers an asset superior to sovereign debt, enabling a new approach to treasury management that promises to eliminate dysfunctional balance sheet practices and revolutionize corporate finance."),
("$ell the Past. ₿uy the Future."),
("Bitcoin is Better Money."),
("In time, you'll forget the price you paid but remember the Bitcoin you bought."),
("Thank You, Satoshi."),
("Pizza keeps getting cheaper on a Bitcoin Standard."),
("Nothing is more powerful than an idea whose time has come."),
("Stay Humble. Stack Sats."),
("You do not sell your Bitcoin."),
("Bitcoin is Cyber Manhattan."),
("1 BTC = 1 BTC."),
("Nothing has created more wealth in the past decade than technologies banned in China."),
("The Bitcoin price is set by those with more money and less knowledge than you. In time, they will get the knowledge and you will get the money.");
